package com.idorasi.compiler.modules;

public enum Atoms {

    ID,END,
    CT_INT,CT_REAL,CT_STRING,CT_CHAR,
    COMMA,SEMICOLON,LPAR,RPAR,LBRACKET,RBRACKET,LACC,RACC,
    ADD,SUB,MUL,DIV,DOT,AND,OR,NOT,ASSIGN,EQUAL,NOTEQ,LESS,LESSEQ,GREATER,GREATEREQ,
    SPACE,LINECOMMENT,COMMENT,
    BREAK,CHAR,DOUBLE,ELSE,FOR,IF,INT,RETURN,STRUCT,VOID,WHILE
}
